### ISSUE TITLE
Unhandled asynchronous exception: TypeError: this.suite[option] is not a function

### ISSUE THREAD

**Issue by stevenlafl** [mocha-parallel/mocha-parallel-tests#295]
Test code:
```
describe('test', () => {
  it('tests', async () => {
  });
});
```
I have tried many different tests I could run under mocha, but this is the simplest that fails.

Starting with `mocha-parallel-tests -R xunit --timeout 10000 --slow 1000 tests/*.test.js`

**Comment by mastermatt** [comment]
I started to see this after upgrading Mocha to v8.x.

**Comment by 1999** [comment]
@mastermatt out of interest, mocha@8 supports parallel mode, does it work for you?

**Comment by mastermatt** [comment]
Using the parallel mode out of the box in mocha 8 isn't straight forward in my case. I'm moving in that direction, but I was hoping to continue using  `mocha-parallel-tests` in the mean time.

**Comment by Pritam-RoyChowdhury** [comment]
Any updated on this issue?
